let token = '', selectedJob = null, extraSources=[], includedLeads=[];
const $ = s => document.querySelector(s);
function el(tag, text, cls) { const node=document.createElement(tag); if(text!==undefined)node.textContent=text; if(cls)node.className=cls; return node; }
function notice(text, error=false){$('#notice').textContent=text;$('#notice').classList.toggle('error',error);}
async function api(path, data){const response=await fetch(path,{method:data===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error||'Request failed');return result;}
function safe(fn){return async event=>{event?.preventDefault();const control=event?.currentTarget?.matches('button')?event.currentTarget:event?.currentTarget?.querySelector('button[type=submit],button:not([type])');if(control)control.disabled=true;try{await fn(event);}catch(error){notice(error.message,true);}finally{if(control)control.disabled=false;}};}
async function refresh(){const overview=await api('/v1/overview');const jobs=overview.jobs;$('#jobs').replaceChildren();$('#job-count').textContent=jobs.length+' jobs';if(!jobs.length)$('#jobs').append(el('p','No drafts yet. Start with a specific reader problem and evidence you can use.','empty'));for(const job of jobs){const button=el('button',undefined,'job '+job.state);button.append(el('small',job.id),el('strong',job.state+' · '+job.provider),el('span',job.error||'Open draft and saved stages'));button.addEventListener('click',safe(()=>showJob(job.id)));$('#jobs').append(button);}$('#runtime').textContent='Model: '+overview.configuration.model+' · Mail '+(overview.configuration.mail?'enabled':'off')+' · Inbox '+(overview.configuration.inbox?'enabled':'off')+' · Payments '+overview.configuration.payment_mode;populateSelect($('#advisor-job'),jobs.filter(j=>j.state==='ready').map(j=>[j.id,j.id.slice(0,8)+' · '+j.provider]));await Promise.all([loadResearch(),loadLeads(),loadCampaigns(),loadStore(),loadAdviser()]);}
async function showJob(id){selectedJob=await api('/v1/jobs/'+id);const area=$('#job-detail');area.hidden=false;area.replaceChildren(el('h2',selectedJob.brief.topic),el('p',selectedJob.brief.audience));const actions=el('div',undefined,'actions');if(selectedJob.state==='ready'){actions.append(action('Download product',()=>download('/v1/export/'+id,'product.zip')),action('Approve product & price',()=>approveProduct(id)));}if(selectedJob.state==='failed')actions.append(action('Retry saved job',async()=>{await api('/v1/jobs/retry',{id});notice('Job queued from saved stages.');await refresh();}));area.append(actions);const rail=el('div',undefined,'steps');for(const name of Object.keys(selectedJob.artifacts))rail.append(el('span',name.replaceAll('_',' '),'done'));area.append(rail);for(const [name,a] of Object.entries(selectedJob.artifacts)){const details=el('details');details.append(el('summary',name.replaceAll('_',' ')+' · '+a.title),el('pre',a.body),el('small','Sources: '+a.citations.join(', ')));if(selectedJob.state==='ready')details.append(action('Edit this draft',()=>editArtifact(id,name,a)));area.append(details);} }
$('#login').addEventListener('submit',safe(async()=>{token=$('#token').value;await refresh();$('#token').value='';$('#connection').hidden=true;$('#workspace').hidden=false;notice('Workspace unlocked.');}));
$('#refresh').addEventListener('click',safe(refresh));
$('#brief-form').addEventListener('submit',safe(async e=>{const f=new FormData(e.target);const brief={id:'product-'+Date.now(),topic:f.get('topic'),audience:f.get('audience'),problem:f.get('problem'),format:f.get('format'),chapter_count:Number(f.get('chapter_count')),sources:[{title:f.get('source_title'),url:f.get('source_url'),text:f.get('source_text'),rights:f.get('rights')},...extraSources],creators:includedLeads};const result=await api('/v1/jobs',{brief,provider:f.get('provider')});notice('Draft queued. The worker saves progress after each stage.');await refresh();await showJob(result.id);}));

// All untrusted text is rendered with textContent or form values, never as HTML.
function action(label,fn,cls='secondary'){const b=el('button',label,cls);b.type='button';b.addEventListener('click',safe(fn));return b;}
function field(label,name,value='',type='text'){const l=el('label',label);const input=el(type==='textarea'?'textarea':'input');if(type!=='textarea')input.type=type;else input.rows=5;input.name=name;input.value=value;input.required=true;l.append(input);return l;}
function modal(title){let d=$('#editor-dialog');if(d)d.remove();d=el('dialog');d.id='editor-dialog';d.append(el('h2',title),action('Close',()=>d.close()));document.body.append(d);d.showModal();return d;}
function populateSelect(select,options){const old=select.value;select.replaceChildren();for(const [value,title] of options){const option=el('option',title);option.value=value;select.append(option);}if(options.some(o=>o[0]===old))select.value=old;}
async function download(path,name){const response=await fetch(path,{headers:{Authorization:'Bearer '+token}});if(!response.ok)throw Error((await response.json()).error);const url=URL.createObjectURL(await response.blob());const link=el('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function view(name){document.querySelectorAll('.view').forEach(n=>n.hidden=n.id!=='view-'+name);document.querySelectorAll('[data-view]').forEach(n=>n.classList.toggle('active',n.dataset.view===name));$('#page-title').textContent=titles[name];}
const titles={studio:'Product studio',research:'Research library',leads:'Creator shortlist',campaigns:'Outreach & inbox',store:'Store & orders',advisor:'Independent adviser'};
for(const [name,title] of Object.entries(titles)){if(name==='studio')continue;const b=el('button',title);b.dataset.view=name;$('#navigation').append(b);}
$('#navigation').addEventListener('click',e=>{if(e.target.dataset.view)view(e.target.dataset.view);});
const chapterLabel=field('Chapters (3–12)','chapter_count','6','number');chapterLabel.querySelector('input').min=3;chapterLabel.querySelector('input').max=12;$('#brief-form').prepend(chapterLabel);
const contextNote=el('p','No additional library sources or creator notes selected.','footnote');contextNote.id='context-note';$('#brief-form').append(contextNote);
function contextCount(){contextNote.textContent=extraSources.length+' additional sources · '+includedLeads.length+' creators included. Total source text and creator notes must fit 16,000 characters.';}
const runtime=el('p','','footnote');runtime.id='runtime';$('#workspace').prepend(runtime);
$('#workspace').insertAdjacentHTML('beforeend', `
<section class="view" id="view-research" hidden><div class="columns"><section class="panel"><h2>Read a public source</h2><p>Imports a bounded excerpt. Login walls, restricted networks and robots exclusions are not bypassed.</p><form id="fetch-source"><label>Article or creator website URL<input name="url" type="url" required></label><label>Usage basis<select name="rights"><option value="public_reference">Public reference · paraphrase only</option><option value="owned">My content</option><option value="permission">Permission granted</option><option value="licensed">Licensed</option></select></label><button>Fetch source</button></form><hr><h2>Find sources</h2><form id="research-search"><label>Research question<input name="query" required></label><button>Search with Brave</button></form><p class="footnote">Requires your Brave API key. Search snippets are not full-page research.</p><div id="research-results" class="stack"></div></section><section class="panel"><h2>Saved evidence</h2><div id="sources" class="stack"></div></section></div></section>
<section class="view" id="view-leads" hidden><div class="columns"><section class="panel"><h2>Discover creators</h2><form id="discover-leads"><label>Niche and audience<input name="query" required placeholder="Educational creators teaching productivity"></label><label>Search service<select name="source"><option value="brave">Brave web search</option><option value="youtube">YouTube channels</option></select></label><button>Find candidates</button></form><p class="footnote">Your API key is required. Results are unqualified candidates—not customers or permission to contact them. Emails are never guessed.</p><div id="discovery-results" class="stack"></div><div class="actions"><button type="button" id="new-lead" class="secondary">Add a creator manually</button></div></section><section class="panel"><h2>Review shortlist</h2><div id="leads" class="stack"></div></section></div></section>
<section class="view" id="view-campaigns" hidden><div class="columns"><section class="panel"><h2>Create a reviewed A/B campaign</h2><form id="campaign-form"><label>Campaign name<input name="name" required></label><label>Subject<input name="subject" required maxlength="200" value="A useful resource for your audience"></label><label>Variant A<textarea name="body_a" rows="5" required>Hello {name}, I am developing an original resource about {niche}. May I share a short outline for your feedback?</textarea></label><label>Variant B<textarea name="body_b" rows="5" required>Hello {name}, would a practical checklist about {niche} be useful to your audience? I would like to discuss whether a small collaboration makes sense.</textarea></label><label>Optional follow-up<textarea name="followup" rows="3"></textarea></label><label>Follow-up delay (hours)<input name="delay_hours" type="number" min="24" max="720" value="72"></label><fieldset><legend>Qualified recipients</legend><div id="campaign-leads"></div></fieldset><button>Create drafts for review</button></form><div id="campaign-metrics" class="stack"></div></section><section class="panel"><h2>Message review queue</h2><div id="mail-queue" class="stack"></div><div class="section-heading"><h2>Correlated replies</h2><button type="button" class="secondary" id="sync-inbox">Sync inbox</button></div><p class="footnote">Only replies matching a sent message and its recipient are imported. Every matched reply stops follow-ups; you label interest yourself.</p><div id="replies" class="stack"></div></section></div></section>
<section class="view" id="view-store" hidden><div class="columns"><section class="panel"><h2>Build a product page</h2><p>Approve a finished draft in Product studio first. Choose sections, edit the copy and preview before publishing.</p><form id="store-form"><label>Approved product<select name="product_id" id="store-product" required></select></label><label>Headline<input name="headline" required maxlength="200"></label><label>Product description<textarea name="description" rows="3" required></textarea></label><label>Seller / brand name<input name="seller_name" required></label><label>Support email<input name="support_email" type="email" required></label><label>Free sample<textarea name="sample" rows="5" required></textarea></label><label>Refund policy<textarea name="refund_policy" rows="3" required></textarea></label><label>Sale terms<textarea name="terms" rows="3" required></textarea></label><h3>Page sections</h3><div id="page-blocks" class="stack"></div><button type="button" class="secondary" id="add-block">Add section</button><label class="check"><input type="checkbox" name="reviewed">I reviewed content accuracy, usage rights, merchant details and sale terms.</label><label class="check"><input type="checkbox" name="published">Publish this page on this server</label><div class="actions"><button>Save page</button><button type="button" class="secondary" id="preview-page">Preview layout</button></div></form></section><section class="panel"><h2>Pages &amp; delivery</h2><div id="store-pages" class="stack"></div><h2>Orders</h2><div id="orders" class="table-wrap"></div><h2>Traffic &amp; receipts</h2><div id="analytics"></div></section></div></section>
<section class="view" id="view-advisor" hidden><div class="columns"><section class="panel"><h2>Ask about your product</h2><p>Uses the chosen project's evidence. This is an independent assistant, not Iman or his private training material.</p><form id="advisor-form"><label>Completed draft<select name="job_id" id="advisor-job" required></select></label><label>Question<textarea name="question" rows="5" required maxlength="2000" placeholder="What evidence is missing before we test this offer?"></textarea></label><button>Ask local AI</button></form></section><section class="panel"><h2>Saved advice</h2><div id="advice" class="stack"></div></section></div></section>`);

async function editArtifact(id,stage,a){const d=modal('Edit draft · '+stage);const f=el('form');f.append(field('Title','title',a.title),field('Body','body',a.body,'textarea'),field('Source IDs (comma-separated)','citations',a.citations.join(', ')),el('button','Save revision'));f.addEventListener('submit',safe(async()=>{const values=new FormData(f);await api('/v1/artifacts/edit',{job_id:id,stage,artifact:{title:values.get('title'),body:values.get('body'),citations:values.get('citations').split(',').map(s=>s.trim()).filter(Boolean)}});d.close();await showJob(id);notice('Revision saved. Approved products cannot be changed.');}));d.append(f);}
function approveProduct(id){const d=modal('Approve a reviewed product');const f=el('form');f.append(el('p','This locks the product contents and price. Review all chapters and evidence first.'),field('Product URL slug','id','','text'),field('Price in minor units (9900 = INR 99)','amount','9900','number'),field('Currency','currency','INR'),field('Partner share basis points (3000 = 30%)','partner_bps','0','number'));const consent=el('label','I have reviewed this draft and approve these contents and price.','check');const box=el('input');box.type='checkbox';box.required=true;consent.prepend(box);f.append(consent,el('button','Approve product'));f.addEventListener('submit',safe(async()=>{const v=Object.fromEntries(new FormData(f));await api('/v1/products',{...v,job_id:id,amount:Number(v.amount),partner_bps:Number(v.partner_bps)});d.close();await loadStore();view('store');notice('Product approved. Build its page next.');}));d.append(f);}
async function loadResearch(){const sources=await api('/v1/research');const target=$('#sources');target.replaceChildren();if(!sources.length)target.append(el('p','No imported evidence yet. Fetch a permitted source or use your own notes in Product studio.','empty'));for(const source of sources){const card=el('article',undefined,'card');card.append(el('h3',source.title),sourceLink(source.url),el('p',source.text.slice(0,450)),el('small',(source.evidence_type||'operator notes')+(source.truncated?' · excerpt truncated':'')));const a=el('div',undefined,'actions');a.append(action('Use as primary source',()=>{const f=$('#brief-form');for(const [name,value] of Object.entries({source_title:source.title,source_url:source.url,source_text:source.text,rights:source.rights}))f.elements[name].value=value;view('studio');notice('Source inserted. Choose a topic and audience.');}),action('Add to current brief',()=>{if(extraSources.some(s=>s.url===source.url))return;extraSources.push(source);contextCount();notice('Additional source included in the next draft.');}));card.append(a);target.append(card);}}
function sourceLink(url){const a=el('a',url);try{const parsed=new URL(url);if(['http:','https:'].includes(parsed.protocol)){a.href=url;a.target='_blank';a.rel='noreferrer';}}catch{}return a;}
$('#fetch-source').addEventListener('submit',safe(async e=>{await api('/v1/research/fetch',Object.fromEntries(new FormData(e.target)));await loadResearch();notice('Source excerpt saved. Check relevance and usage rights.');}));
$('#fetch-source').append(action('Import public YouTube captions',async()=>{await api('/v1/research/youtube',Object.fromEntries(new FormData($('#fetch-source'))));await loadResearch();notice('Public caption excerpt saved. It does not verify visual-only content.');}));
$('#research-search').addEventListener('submit',safe(async e=>{const found=await api('/v1/research/search',Object.fromEntries(new FormData(e.target)));const target=$('#research-results');target.replaceChildren();for(const r of found){const c=el('article',undefined,'card');c.append(el('h3',r.title),sourceLink(r.url),el('p',r.text),action('Fetch and save page',async()=>{await api('/v1/research/fetch',{url:r.url,rights:'public_reference'});await loadResearch();notice('Page excerpt saved.');}));target.append(c);}if(!found.length)target.append(el('p','No results for this query.'));}));
function editLead(lead={}){const d=modal('Review creator');const f=el('form');for(const [label,key,type] of [['Name','name','text'],['Profile URL','profile_url','url'],['Niche','niche','text'],['Audience evidence','audience_notes','textarea'],['Verified contact email (optional)','email','email'],['Contact basis / permission','contact_basis','textarea']]){const n=field(label,key,lead[key]||'',type);if(['email','contact_basis'].includes(key))n.querySelector('input,textarea').required=false;f.append(n);}const l=el('label','Qualification');const select=el('select');select.name='status';populateSelect(select,['review','qualified','declined'].map(s=>[s,s]));select.value=lead.status||'review';l.append(select);f.append(l,el('button','Save creator'));f.addEventListener('submit',safe(async()=>{await api('/v1/leads',{...lead,...Object.fromEntries(new FormData(f))});d.close();await loadLeads();notice('Creator saved. Saving does not send a message.');}));d.append(f);}
$('#new-lead').addEventListener('click',()=>editLead());
$('#discover-leads').addEventListener('submit',safe(async e=>{const found=await api('/v1/discover',Object.fromEntries(new FormData(e.target)));const target=$('#discovery-results');target.replaceChildren();for(const r of found){const c=el('article',undefined,'card');c.append(el('h3',r.name),sourceLink(r.profile_url),el('p',r.audience_notes),el('small',r.evidence_type),action('Review candidate',()=>editLead(r)));target.append(c);}if(!found.length)target.append(el('p','No candidates found. Try a more specific niche.'));}));
async function loadLeads(){const leads=await api('/v1/leads');const target=$('#leads');target.replaceChildren();$('#campaign-leads').replaceChildren();for(const lead of leads){const c=el('article',undefined,'card');c.append(el('h3',lead.name),el('span',lead.status,'tag'),el('p',lead.audience_notes),sourceLink(lead.profile_url));const a=el('div',undefined,'actions');a.append(action('Review / edit',()=>editLead(lead)),action('Include in product brief',()=>{if(!includedLeads.some(l=>l.profile_url===lead.profile_url))includedLeads.push(lead);contextCount();notice('Creator notes included in the next product brief.');}));c.append(a);target.append(c);if(lead.status==='qualified'&&lead.email){const l=el('label',lead.name+' · '+lead.email,'check');const box=el('input');box.type='checkbox';box.name='lead_ids';box.value=lead.id;l.prepend(box);$('#campaign-leads').append(l);}}if(!leads.length)target.append(el('p','No creators saved. Discover candidates or add a permissioned contact.','empty'));}
$('#campaign-form').addEventListener('submit',safe(async e=>{const f=new FormData(e.target);const result=await api('/v1/campaigns',{...Object.fromEntries(f),lead_ids:f.getAll('lead_ids'),delay_hours:Number(f.get('delay_hours'))});notice(result.drafts+' drafts created. Review each message before approval.');await loadCampaigns();}));
async function loadCampaigns(){const [campaigns,messages,replies]=await Promise.all(['/v1/campaigns','/v1/mail','/v1/replies'].map(p=>api(p)));$('#campaign-metrics').replaceChildren();for(const c of campaigns){const item=el('article',undefined,'card');item.append(el('h3',c.name),el('p',c.recommendation));for(const v of c.variants)item.append(el('p',v.variant+': '+v.drafted+' drafts · '+v.sent+' sent · '+v.replied+' replies · '+v.interested+' interested'));$('#campaign-metrics').append(item);}$('#mail-queue').replaceChildren();for(const m of messages){const c=el('details',undefined,'card');c.append(el('summary',m.recipient+' · '+m.state),el('h3',m.subject),el('pre',m.body),el('p','Contact basis: '+m.evidence),el('p','Scheduled: '+new Date(m.due*1000).toLocaleString()));const a=el('div',undefined,'actions');if(m.state==='draft')a.append(action('Edit',()=>editMessage(m)),action('Approve this message',async()=>{await api('/v1/mail/approve',{id:m.id});notice('Message approved. Delivery still requires configured SMTP.');await loadCampaigns();}));if(['draft','approved'].includes(m.state))a.append(action('Cancel',async()=>{await api('/v1/mail/cancel',{id:m.id});await loadCampaigns();}));c.append(a);$('#mail-queue').append(c);}if(!messages.length)$('#mail-queue').append(el('p','No messages queued.','empty'));$('#replies').replaceChildren();for(const r of replies){const c=el('details',undefined,'card');c.append(el('summary',r.sender+' · '+r.status),el('h3',r.subject),el('pre',r.body));const a=el('div',undefined,'actions');for(const status of ['interested','not-interested','opt-out','automatic'])a.append(action(status,async()=>{await api('/v1/replies/label',{id:r.id,status});await loadCampaigns();}));c.append(a);$('#replies').append(c);}if(!replies.length)$('#replies').append(el('p','No correlated replies imported. Enable IMAP in private configuration to sync your own mailbox.','empty'));}
function editMessage(m){const d=modal('Edit message');const f=el('form');f.append(field('Subject','subject',m.subject),field('Body','body',m.body,'textarea'),el('button','Save draft'));f.addEventListener('submit',safe(async()=>{await api('/v1/mail/edit',{id:m.id,...Object.fromEntries(new FormData(f))});d.close();await loadCampaigns();}));d.append(f);}
$('#sync-inbox').addEventListener('click',safe(async()=>{const result=await api('/v1/inbox/sync',{});notice(result.enabled?result.imported+' replies imported.':'IMAP is disabled. Configure your own mailbox first.');await loadCampaigns();}));
let storePages=[];
function addBlock(heading='',body=''){const block=el('div',undefined,'editor-block');block.append(field('Section heading','heading',heading),field('Section content','body',body,'textarea'));const a=el('div',undefined,'actions');a.append(action('Move up',()=>{if(block.previousElementSibling)block.parentNode.insertBefore(block,block.previousElementSibling);}),action('Move down',()=>{if(block.nextElementSibling)block.parentNode.insertBefore(block.nextElementSibling,block);}),action('Remove section',()=>block.remove()));block.append(a);$('#page-blocks').append(block);}
function loadPageForm(){const page=storePages.find(p=>p.product_id===$('#store-product').value);const f=$('#store-form');for(const key of ['headline','description','seller_name','support_email','sample','refund_policy','terms'])f.elements[key].value=page?.content[key]||'';f.elements.published.checked=!!page?.published;f.elements.reviewed.checked=false;$('#page-blocks').replaceChildren();for(const b of page?.content.blocks||[{heading:'What you will learn',body:''}])addBlock(b.heading,b.body);}
function pageValues(){const f=$('#store-form');return {...Object.fromEntries(new FormData(f)),reviewed:f.elements.reviewed.checked,published:f.elements.published.checked,blocks:[...$('#page-blocks').children].map(b=>({heading:b.querySelector('[name=heading]').value,body:b.querySelector('[name=body]').value}))};}
$('#store-product').addEventListener('change',loadPageForm);$('#add-block').addEventListener('click',()=>addBlock());
$('#preview-page').addEventListener('click',()=>{const p=pageValues();const d=modal('Page preview · not published');d.append(el('small',p.seller_name),el('h1',p.headline||'Your headline'),el('p',p.description));for(const b of p.blocks){const section=el('section',undefined,'store-section');section.append(el('h2',b.heading),el('div',b.body,'prose'));d.append(section);}d.append(el('h2','Refund policy'),el('p',p.refund_policy),el('h2','Sale terms'),el('p',p.terms));});
$('#store-form').addEventListener('submit',safe(async()=>{const result=await api('/v1/storefronts',pageValues());notice(result.published?'Page published on this server. Public internet access still depends on hosting.':'Page saved privately.');await loadStore();}));
async function loadStore(){const [products,pages,orders,analytics]=await Promise.all(['/v1/products','/v1/storefronts','/v1/orders','/v1/analytics'].map(p=>api(p)));storePages=pages;const wasEmpty=!$('#store-product').options.length;populateSelect($('#store-product'),products.map(p=>[p.id,p.id+' · '+p.currency+' '+(p.amount/100).toFixed(2)]));if(wasEmpty)loadPageForm();$('#store-pages').replaceChildren();for(const p of pages){const c=el('article',undefined,'card');c.append(el('h3',p.content.headline),el('span',p.published?'published on server':'private draft','tag'));const a=el('div',undefined,'actions');a.append(action('Edit page',()=>{$('#store-product').value=p.product_id;loadPageForm();}),action('Export page preview ZIP',()=>download('/v1/funnel-export/'+p.product_id,'funnel-preview.zip')));if(p.published){const link=el('a','Open product page','button secondary');link.href='/p/'+p.product_id;link.target='_blank';link.rel='noreferrer';a.append(link);}c.append(a);$('#store-pages').append(c);}if(!pages.length)$('#store-pages').append(el('p','No pages yet. Approve a draft, then build and publish its page.','empty'));table($('#orders'),['Product','Mode','State','Amount'],orders.map(o=>[o.product_id,o.mode,o.state,o.currency+' '+(o.amount/100).toFixed(2)]));$('#analytics').replaceChildren(el('p',analytics.note));for(const row of analytics.page_requests)$('#analytics').append(el('p',row.product_id+' / '+row.page+': '+row.requests+' requests'));for(const row of analytics.orders)$('#analytics').append(el('p',row.product_id+' · '+row.mode+' · '+row.state+': '+row.orders+' orders'));}

const transferPanel=el('section',undefined,'panel');transferPanel.append(el('h2','Partner transfers'),el('p','Razorpay Route requires approved Linked Accounts. Plan the accrued gross share, review the exact recipient and amount, then approve it. The worker sends only when Route is explicitly enabled; a submitted transfer is not proof of bank settlement.'));
const transferForm=el('form');transferForm.append(field('Paid order ID','order_id'),field('Verified partner Linked Account ID','account'),el('button','Prepare transfer for review'));const transferList=el('div',undefined,'stack');transferPanel.append(transferForm,transferList);$('#view-store').append(transferPanel);
transferForm.addEventListener('submit',safe(async()=>{const result=await api('/v1/transfers/plan',Object.fromEntries(new FormData(transferForm)));notice('Transfer draft prepared. No funds sent.');await loadTransfers();}));
async function loadTransfers(){const rows=await api('/v1/transfers');transferList.replaceChildren();for(const t of rows){const c=el('article',undefined,'card');c.append(el('h3',t.currency+' '+(t.amount/100).toFixed(2)+' → '+t.account),el('p',t.mode+' · '+t.state),el('small',t.error||'Provider reference: '+(t.provider_id||'not submitted')));if(t.state==='draft')c.append(action('Review transfer approval',()=>{const d=modal('Approve this exact partner transfer?');d.append(el('p','Recipient: '+t.account),el('p','Amount: '+t.currency+' '+(t.amount/100).toFixed(2)),el('p','Mode: '+t.mode+'. Approval authorizes the worker to submit this transfer once matching credentials and transfer flags are enabled.'),action('Approve '+t.currency+' '+(t.amount/100).toFixed(2),async()=>{await api('/v1/transfers/approve',{id:t.id,amount:t.amount,account:t.account});d.close();await loadTransfers();notice('Transfer approved. It remains subject to provider configuration.');},''));}));transferList.append(c);}if(!rows.length)transferList.append(el('p','No partner transfers planned.','empty'));}
const originalLoadStore=loadStore;loadStore=async()=>{await originalLoadStore();await loadTransfers();const orders=await api('/v1/orders');for(const o of orders.filter(o=>o.state==='paid'&&o.mode!=='demo'))$('#orders').append(action('Plan share for order '+o.id,()=>{transferForm.elements.order_id.value=o.id;transferPanel.scrollIntoView({block:'start'});}));};
function table(target,head,rows){target.replaceChildren();if(!rows.length){target.append(el('p','No records yet.','empty'));return;}const t=el('table'),thead=el('thead'),tr=el('tr');head.forEach(h=>tr.append(el('th',h)));thead.append(tr);t.append(thead);const body=el('tbody');for(const row of rows){const r=el('tr');row.forEach(c=>r.append(el('td',String(c))));body.append(r);}t.append(body);target.append(t);}
async function loadAdviser(){const results=await api('/v1/advisor');$('#advice').replaceChildren();for(const r of results){const c=el('article',undefined,'card');c.append(el('h3',r.question),el('pre',r.answer.body),el('small','Sources: '+r.answer.citations.join(', ')));$('#advice').append(c);}if(!results.length)$('#advice').append(el('p','No advice saved yet. Choose a draft and ask a concrete question.','empty'));}
$('#advisor-form').addEventListener('submit',safe(async e=>{notice('The local model is considering your question. This may take several minutes.');await api('/v1/advisor',Object.fromEntries(new FormData(e.target)));await loadAdviser();notice('Advice saved. Check its reasoning against the sources.');}));
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{document.modelContext.registerTool({name:'list_draft_jobs',title:'List product drafts',description:'Read the authenticated operator draft queue. Does not create, publish or send anything.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async input=>{if(!input||Object.keys(input).length)throw Error('No inputs accepted.');const jobs=await api('/v1/jobs');await refresh();return jobs;}},{signal:lifecycle.signal});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
